import os
from datetime import datetime
from PIL import Image, ImageDraw, ImageFont

# Try to import Vertex AI modules
try:
    import vertexai
    from vertexai.preview.vision_models import ImageGenerationModel

    _VERTEX_AVAILABLE = True
except ImportError:
    _VERTEX_AVAILABLE = False

GENERATED_IMAGES_DIR = "generated_images"


def generate_image(api_key=None, prompt: str = "", project_id=None, location=None):
    """
    Generates an image using Vertex AI (Imagen) if available/configured,
    otherwise falls back to placeholder.
    """
    print(f"Generating image for prompt: '{prompt[:50]}...'")

    # Ensure directory exists
    if not os.path.exists(GENERATED_IMAGES_DIR):
        os.makedirs(GENERATED_IMAGES_DIR)

    # timestamp for filename
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S%f")
    filename = f"gen_{timestamp}.png"
    filepath = os.path.join(GENERATED_IMAGES_DIR, filename)

    if _VERTEX_AVAILABLE and project_id and location:
        try:
            # Initialize Vertex AI for image generation
            # Note: Image generation often requires a regional endpoint like us-central1
            # even if Gemini models use 'global'.
            img_location = location
            if location == "global":
                img_location = "us-central1"

            vertexai.init(project=project_id, location=img_location)

            # Load model (Imagen 3 - replaces EOL imagegeneration@006)
            model = ImageGenerationModel.from_pretrained("imagen-3.0-generate-002")

            # Generate
            images = model.generate_images(
                prompt=prompt,
                number_of_images=1,
                aspect_ratio="4:3",  # Match placeholder 400x300 roughly
                safety_filter_level="block_some",
                person_generation="allow_adult",
            )

            if images:
                images[0].save(filepath)
                print(f"Image successfully generated by Vertex AI: {filepath}")
                return filepath
        except Exception as e:
            print(f"Vertex AI Image Generation failed: {e}")

    # Fallback
    print("Falling back to placeholder image.")
    return create_placeholder_image(prompt)


def create_placeholder_image(text):
    if not os.path.exists(GENERATED_IMAGES_DIR):
        os.makedirs(GENERATED_IMAGES_DIR)

    timestamp = datetime.now().strftime("%Y%m%d%H%M%S%f")
    filename = f"placeholder_{timestamp}.png"
    filepath = os.path.join(GENERATED_IMAGES_DIR, filename)

    # Create image
    width, height = 400, 300
    img = Image.new("RGB", (width, height), color=(230, 230, 230))
    d = ImageDraw.Draw(img)

    # Draw text
    try:
        # Try to use a standard font if available
        font = ImageFont.truetype("arial.ttf", 14)
        title_font = ImageFont.truetype("arial.ttf", 20)
    except IOError:
        # Fallback to default font
        font = ImageFont.load_default()
        title_font = ImageFont.load_default()

    # Draw Title
    d.text(
        (20, height / 2 - 40), "AI Image Placeholder", fill=(0, 0, 0), font=title_font
    )

    # Wrap text
    margin = 20
    offset = height / 2
    for line in text_wrap(text, font, width - 2 * margin):
        d.text((margin, offset), line, fill=(0, 0, 0), font=font)
        offset += 15

    img.save(filepath)
    return filepath


def text_wrap(text, font, max_width):
    lines = []
    try:
        font.getlength("a")
    except AttributeError:
        # Fallback for very old Pillow or default font limitations
        return [text[i : i + 50] for i in range(0, len(text), 50)]

    words = text.split()
    if not words:
        return []

    current_line = words[0]
    for word in words[1:]:
        if font.getlength(current_line + " " + word) <= max_width:
            current_line += " " + word
        else:
            lines.append(current_line)
            current_line = word
    lines.append(current_line)
    return lines
